# Generated by Django 3.0.2 on 2020-01-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaldetails',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('register_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('cgpa', models.IntegerField()),
                ('ph_no', models.IntegerField()),
            ],
        ),
    ]
