# Generated by Django 3.0.2 on 2020-02-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='ph_no',
            field=models.IntegerField(max_length=10),
        ),
    ]
