# Generated by Django 3.0.2 on 2020-02-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200211_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='ph_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='register_no',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
