# Generated by Django 3.0.2 on 2020-02-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200211_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='name',
        ),
    ]
