# Generated by Django 3.0.2 on 2020-04-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_personaldetails_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='name',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='semister',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=2),
        ),
    ]
